### ISSUE TITLE
Error after fetching schema

### ISSUE THREAD

**Issue by chamroeunbm** [parse-server-modules/parse-files-utils#14]
Hi,

I got this error during migration. Any suggestion?

....
Initializing transfer configuration...
Initializing filesystem adapter
Fetching schema...
Fetching all objects with files...
[TypeError: Cannot read property 'name' of null]
---

**Comment by chamroeunbm** [comment]
Here's my config:

module.exports = {
  applicationId: "xxxx",
  masterKey: "xxx",
  mongoURL: "mongodb://xx:xx@x.y.z.z:27017/test",
  serverURL: "https://api.parse.com/1",
  filesToTransfer: 'parseOnly',
  renameInDatabase: false,
  transferTo: 'filesystem',

  // For filesystem configuration
  filesystemPath: './downloaded_files',

**Comment by chamroeunbm** [comment]
Here's what is in the npm-debug log

`

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'start',
1 verbose cli   'config.example.js' ]
2 info using npm@3.10.6
3 info using node@v5.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle parse-files-utils@0.0.1~prestart: parse-files-utils@0.0.1
6 silly lifecycle parse-files-utils@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle parse-files-utils@0.0.1~start: parse-files-utils@0.0.1
8 verbose lifecycle parse-files-utils@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle parse-files-utils@0.0.1~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/test2/parse-files-utils/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle parse-files-utils@0.0.1~start: CWD: /root/test2/parse-files-utils
11 silly lifecycle parse-files-utils@0.0.1~start: Args: [ '-c', 'node index.js "config.example.js"' ]
12 silly lifecycle parse-files-utils@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle parse-files-utils@0.0.1~start: Failed to exec start script
14 verbose stack Error: parse-files-utils@0.0.1 start: `node index.js "config.example.js"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid parse-files-utils@0.0.1
16 verbose cwd /root/test2/parse-files-utils
17 error Linux 4.4.0-28-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start" "config.example.js"
19 error node v5.12.0
20 error npm  v3.10.6
21 error code ELIFECYCLE
22 error parse-files-utils@0.0.1 start: `node index.js "config.example.js"`
22 error Exit status 1

`

**Comment by kanersan** [comment]
I get something like this: 

Initializing transfer configuration...
Initializing filesystem adapter
Fetching schema...
"Cannot GET /schemas\n"

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.7.0/bin/node" "/usr/local/bin/npm" "start" "config.example.js"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! parse-files-utils@0.0.1 start: `node index.js "config.example.js"`
npm ERR! Exit status 1

And I checked under the lib folder where there is a bunch of .js files. In the index.js it seems it's requiring schemas, transfer and questions.js. I added ".js" to schemas and transfer also to see if that would work but no luck.
