### ISSUE TITLE
Error: Cannot find module '/home/bird/parse-files-utils/node_modules/grpc/src/node/extension_binary/grpc_node.node'

### ISSUE THREAD

**Issue by yorkwang** [parse-server-modules/parse-files-utils#21]
bird@ubuntu-512mb-nyc3-01:~/parse-files-utils$ node config.js 
module.js:341
    throw err;
    ^

Error: Cannot find module '/home/bird/parse-files-utils/node_modules/grpc/src/node/extension_binary/grpc_node.node'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/bird/parse-files-utils/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

**Comment by alist** [comment]
What's the solution to this?
