### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by chriswise01** [parse-server-modules/parse-files-utils#25]
Running on Mac OS X with latest node and npm. I followed the installation and setup instructions and after running "npm start" I get the following error: 

`> parse-files-utils@0.0.1 start /Users/chriswise/Documents/Development/Experiments/ParseFileMigrator/parse-files-utils-master

> node index.js

module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 14.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/chriswise/Documents/Development/Experiments/ParseFileMigrator/parse-files-utils-master/node_modules/parse-server-gcs-adapter/node_modules/@google-cloud/storage/node_modules/@google-cloud/common/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! parse-files-utils@0.0.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parse-files-utils@0.0.1 start script 'node index.js'.
npm ERR! This is most likely a problem with the parse-files-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parse-files-utils
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls parse-files-utils
npm ERR! There is likely additional logging output above.
`

**Comment by linktothapast** [comment]
Same here, except I get a different "mismatch" message:

```
Error: Module version mismatch. Expected 48, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ({...}/parse-files-utils/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
```

**Comment by ilyashev** [comment]
same problem: Module version mismatch. Expected 48, got 46.

i was able to run the module successfully before, not sure what has changed.

**Comment by linktothapast** [comment]
We couldn't wait anymore and created our own solution based on this. In case anyone finds it useful:
https://github.com/slidebean/parse-s3-migration

**Comment by ilyashev** [comment]
Thanks @linktothapast. I found a solution to the issue--needed to reinstall node modules after a node update, like so: rm -rf node_modules && npm install.

That took care of the error.

**Comment by mdimarca** [comment]
@linktothapast thanks for fixing this with your repo!! It worked great for me.
