### ISSUE TITLE
npm start error: "Cannot find module 'parse-server-gcs-adapter'"

### ISSUE THREAD

**Issue by heathervv** [parse-server-modules/parse-files-utils#37]
- Running on Mac OS X with node -v7.2.0 and npm -v4.0.5

```
Error: Cannot find module 'parse-server-gcs-adapter'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/heather/Projects/parse-files-utils/lib/transfer.js:6:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! parse-files-utils@0.0.1 start: node index.js
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parse-files-utils@0.0.1 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parse-files-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parse-files-utils
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls parse-files-utils
npm ERR! There is likely additional logging output above.
```

[npm-debug.log.zip](https://github.com/parse-server-modules/parse-files-utils/files/664206/npm-debug.log.zip)

**Comment by dehli** [comment]
There's issues with installing that package. I just commented out the line and it worked fine:
```
//var GCSAdapter = require('parse-server-gcs-adapter');
```

**Comment by heathervv** [comment]
That did it! Thank you!
