### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by reidmweber** [parse-server-modules/parse-files-utils#49]
I successfully migrated our files last week. The file count was around 191,000. 
This week I went to migrate any additional ones that may have shown up from old clients. But I keep getting this error:

Initializing transfer configuration...
Connecting to MongoDB
Successfully connected to MongoDB
Initializing s3 adapter
Fetching schema...
Fetching all objects with files...
Processing 205803 files
Saving files with s3
RangeError: Maximum call stack size exceeded
    at new TickObject (internal/process/next_tick.js:136:26)
    at process.nextTick (internal/process/next_tick.js:154:24)
    at onwrite (_stream_writable.js:350:15)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at WriteStream.Socket._writeGeneric (net.js:714:5)
    at WriteStream.Socket._write (net.js:724:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at WriteStream.Writable.write (_stream_writable.js:220:11)
    at WriteStream.Socket.write (net.js:650:40)

**Comment by sirioz** [comment]
I solved with a small fix directly on code. Look here: https://github.com/parse-server-modules/parse-files-utils/issues/17#issuecomment-269552573

**Comment by reidmweber** [comment]
Thanks. Don't know how I missed that issue. That worked for me. I created a PR for it.
