### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rusmichal** [parse-server-modules/parse-files-utils#55]
Hello,

Yesterday I have started transfer process. I have 80k files and I have already transferred 20k and today I wanted start transfer next 60k and I got that error:

I use Amazon S3 storage.

```
RangeError: Maximum call stack size exceeded
    at process.nextTick (internal/process/next_tick.js:150:22)
    at onwrite (_stream_writable.js:377:15)
    at WritableState.onwrite (_stream_writable.js:90:5)
    at WriteStream.Socket._writeGeneric (net.js:721:5)
    at WriteStream.Socket._write (net.js:731:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:658:40)
    at /Users/moodup/Documents/parse-migration-files-example/lib/transfer.js:134:22
```

**Comment by rusmichal** [comment]
@sirioz solution works for me:
https://github.com/parse-server-modules/parse-files-utils/issues/17#issuecomment-269552573
